### ISSUE TITLE
oath/token request uses GET - no longer allowed by the API

### ISSUE THREAD

**Issue by bfaler** [benweier/blizzard.js#121]
This morning my app started getting 400 Bad Request errors from the API.  It looks like the oath/token request is sending a GET request which is no longer allowed by the API.

https://develop.battle.net/documentation/battle-net/oauth-apis

There was some discussion about a similiar problem back in September and the change was reverted by Blizzard, but it seems to be happening again.

https://us.forums.blizzard.com/en/blizzard/t/api-error-get-method-is-not-allowed/11938

Here is the section of code from my app that is resulting in 400 Bad Request response:

		const wowClient = await blizzard.wow.createInstance({
			key: mainconfig.bnetclientid,
			secret: mainconfig.bnetclientsecret,
			origin: 'us', // optional
			locale: 'en_US', // optional
			token: {} // optional
		}).catch( err => { console.log(err); });

**Comment by benweier** [comment]
Thanks @bfaler could you try removing the `token` property please?

**Comment by bfaler** [comment]
Sure thing.  I removed the token line so now my code is:

		const wowClient = await blizzard.wow.createInstance({
			key: mainconfig.bnetclientid,
			secret: mainconfig.bnetclientsecret,
			origin: 'us', // optional
			locale: 'en_US' // optional
		}).catch( err => { console.log(err); });

Same response from the API (let me know if you'd like the full error):
      error: 'invalid_request',
      error_description: 'GET method is not allowed, use POST method instead.'

It was working great until this morning.

**Comment by bfaler** [comment]
Blizzard has now confirmed that this was a intentional and poorly communicated change.

https://us.forums.blizzard.com/en/blizzard/t/http-get-deprecated-for-oauthtoken-endpoint/15232

**Comment by AlexThomas90210** [comment]
@bfaler How did you get around this?

**Comment by bfaler** [comment]
@AlexThomas90210 I haven't been able to work around it yet.  Hopefully @benweier  will have time to look into it further soon.

**Comment by benweier** [comment]
Thanks guys, I have jumped on this today and pushing out a new version shortly

**Comment by benweier** [comment]
`4.0.2` has now been published to npm
