### ISSUE TITLE
locale getting ignored/som missing

### ISSUE THREAD

**Issue by iraizo** [benweier/blizzard.js#128]
This is my current code

```ts
    const client = await wow.classic.createInstance({
        key: config.client_id,
        secret: config.client_secret,
        origin: "eu",
        locale: "en_US",
    });

    await client.getApplicationToken().then(response => {
        config.token = response.data.access_token;
    });

    let x = await client.realmSearch({token: config.token, secret: config.client_secret, locale: "en_US"});
    console.log(JSON.stringify(x.data));
```

The output is **classic era** servers which are in all locales instead of en_US, and the SOM servers are also missing, not sure if thats because of the API or the library

**Comment by Savedyou** [comment]
I believe the wow api only returns the en_US locale for an index of realms and ignores your set locale.  If you look up and individual realm you can use locale of your choice as an argument.  At least I remember getting stuck on something like this in the past.
