### ISSUE TITLE
Missing /wow/auctions/commodities

### ISSUE THREAD

**Issue by Akandesh** [benweier/blizzard.js#131]
New WoW API endpoint: https://us.forums.blizzard.com/en/blizzard/t/immediate-change-to-auction-apis-for-commodities-with-927/31522

**Comment by benweier** [comment]
Thanks @Akandesh I'll jump on this as soon as I can

**Comment by benweier** [comment]
@Akandesh `4.3.0` has been published to npm with the `wow.commodities` method
