### ISSUE TITLE
Character PvP Bracket Statistics missing

### ISSUE THREAD

**Issue by oliv-tree** [benweier/blizzard.js#176]
Hey,

Doesn't seem like there is currently a way to access the `/profile/wow/character/{realmSlug}/{characterName}/pvp-bracket/{pvpBracket}` endpoint?

**Comment by benweier** [comment]
Hey @oliv-tree, the `wow.characterPVP` method has implemented this endpoint for the retail client. Are you looking for this on the classic client?

**Comment by oliv-tree** [comment]
> Hey @oliv-tree, the `wow.characterPVP` method has implemented this endpoint for the retail client. Are you looking for this on the classic client?

My bad - I was not aware of exactly how the endpoints functioned. I was making the call without the `bracket` field.

**Comment by benweier** [comment]
I could definitely improve the docs to make this clearer. I'll see what I can do in the coming days
