### ISSUE TITLE
Newer WoW Classic APIs Missing

### ISSUE THREAD

**Issue by bfaler** [benweier/blizzard.js#194]
Was trying to update one of my projects using your library to support a guild contest my guild is running this month and I noticed it looks like the APIs that were made public with 1.14.4 aren't implemented.  I could be missing something.. but at least in the documentation they aren't listed.

Any chance of an update to include any of these?  (Specifically these are Character and Guild information that was previously unavailable in Classic)

https://us.forums.blizzard.com/en/wow/t/new-apis-now-available-for-testing/1645500
https://develop.battle.net/documentation/world-of-warcraft-classic/profile-apis

Regardless, thank you for this library!  It has been a huge help over the years!

**Comment by benweier** [comment]
Thanks for letting me know @bfaler! `v4.6.0` has been published to npm. I appreciate the kind words and I'm glad this has helped your project :)
