### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by khay** [benweier/blizzard.js#23]
Hi, I would like to know is there any way to handle errors for **Unhandled promise rejection** ?

Thanks

**Comment by benweier** [comment]
Hi @khay, blizzard.js doesn't handle resolved or rejected promises but returns the promise object itself. You should include a `catch()` statement when calling any blizzard.js method.

for example
```
blizzard.wow.character(['profile'], { name, realm, origin })
  .then(response => console.log(response.data))
  .catch(err => console.log(err.response.data));
```
will log a successful request (a resolved promise) and log a failed request (a failed promise).
