### ISSUE TITLE
Add Typescript definitions (.d.ts)

### ISSUE THREAD

**Issue by dlopes7** [benweier/blizzard.js#27]
It would be great to have a .d.ts file with the typings so that it would be easier to use this great library with Typescript (@types/blizzard.js)

**Comment by benweier** [comment]
Thanks @dlopes7 I'll look at what I need to do for this

**Comment by markhaehnel** [comment]
Any update on this?

**Comment by benweier** [comment]
I have spent some time looking into definitions files but I haven't developed with Typescript before so it feels very foreign to me. I'd appreciate any help available on how to create typings if someone wants to make a contribution.

**Comment by dlopes7** [comment]
I’ll submit a pull request with it

**Comment by Nerothos** [comment]
Any news about this?

**Comment by benweier** [comment]
I've made 2019 the year I adopt Typescript! And I don't mean "by December", I'm starting my TS education right away and I plan to really do something about this as soon as I can.

**Comment by Nerothos** [comment]
Nice to hear about that ! I've currently moving too ;) Good luck with your education =D
