### ISSUE TITLE
Exporting from response.data

### ISSUE THREAD

**Issue by nkane1997** [benweier/blizzard.js#30]
Hi,

First time picking up any java as well as anything to do with an api. However my aim is to create a discord bot that would feed this information back when prompted. I have managed to setup up my discord bot and configure its commands as well as use your example to pull some information from the API however I am confused as to how to get the data from the response.data and into a string where i can report it back out. 

I was just wondering if you would be able to give me some advice in regards converting the response data which for your example looked like this for me after inputing a name of a player on draenor from wowprogress.

{ lastModified: 1489993871000,
  name: 'Plexandie',
  realm: 'Draenor',
  battlegroup: 'Embuscade / Hinterhalt',
  class: 3,
  race: 8,
  gender: 0,
  level: 110,
  achievementPoints: 15200,
  thumbnail: 'draenor/181/95257781-avatar.jpg',
  calcClass: 'Y',
  faction: 1,
  totalHonorableKills: 270 }

I would like to potentially convert this data into an array where i can call certain parts of it e.g. tooninfo.name = name from the list of data above.
tooninfo.realm = realm etc etc

If you could help me with this issues i would be extremely grateful.

Thanks.

**Comment by benweier** [comment]
Hi @nkane1997 the response data you get back from the API is an object that you can access the properties on using their key in exactly the manner to describe.

e.g. a character with these properties
```
{
  name: 'Plexandie,
  realm: 'Draenor'
  level: 110,
  etc...
}
```

can be accessed from the response object as

```js
blizzard.wow.character(['profile'], { origin: 'us', realm: 'draenor', name: 'plexandie' })
  .then(response => {
    console.log(response.data.name); // => Plexandie
    console.log(response.data.realm); // => Draenor
    console.log(response.data.level); // => 110
  });
```

If you're using `discord.js` for your Discord bot a quick example might look like this

```
const Discord = require('discord.js');
const bot = new Discord.Client();

bot.on('message', message => {

  if (message.content.startsWith('!character')) {
    const [name, realm, origin] = message.content.split(' ');

    blizzard.wow.character(['profile'], { origin, realm, name })
      .then(response => {
        bot.reply(message, JSON.stringify(response.data));
      });
  }
});
```

When you type `!character plexandie draenor us` into Discord, the bot will fetch the character data and respond with the whole API response as a string instead of an object. I don't recommend using it for real but I hope it gives you an idea of where you can go from there.

**Comment by nkane1997** [comment]
Thanks a lot for the help. I am using discord.js-commando and have managed to take the knowledge you have given me and apply it to my script.

Turns out i was just using JSON.stringify wrong and was not quite understanding how response.data worked. 

However i am now able to turn the response data into strings and use switch case statements to convert the id numbers to words e.g. 3 = hunter.

This has been a huge help thanks for the prompt response.

**Comment by nkane1997** [comment]
One further question if i may add. In regards to using 'progression' when i use this it returns
 progression:
   { raids:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },

However on the blizzard api there is loads of different bits of data there such as id, raid name etc. 

My question is how do i access that information and is there a way for me differentiate between raids.

E.G.

        }, {
            "name": "Trial of Valor",
            "lfr": 0,
            "normal": 2,
            "heroic": 2,
            "mythic": 1,
            "id": 8440,
            "bosses": [{
                "id": 115323,
                "name": "Odyn",
                "lfrKills": 0,
                "lfrTimestamp": 0,
                "normalKills": 6,
                "normalTimestamp": 1486235872000,
                "heroicKills": 6,
                "heroicTimestamp": 1485615081000,
                "mythicKills": 2,
                "mythicTimestamp": 1487280947000
            }, {
                "id": 114344,
                "name": "Guarm",
                "lfrKills": 0,
                "lfrTimestamp": 0,
                "normalKills": 6,
                "normalTimestamp": 1486236251000,
                "heroicKills": 6,
                "heroicTimestamp": 1485615825000,
                "mythicKills": 3,
                "mythicTimestamp": 1487282445000
            }, {
                "id": 93394,
                "name": "Helya",
                "lfrKills": 0,
                "lfrTimestamp": 0,
                "normalKills": 6,
                "normalTimestamp": 1486236682000,
                "heroicKills": 2,
                "heroicTimestamp": 1485617030000,
                "mythicKills": 0,
                "mythicTimestamp": 0
            }]
        }, {
            "name": "The Nighthold",
            "lfr": 1,
            "normal": 2,
            "heroic": 2,
            "mythic": 1,
            "id": 8025,
            "bosses": [{
                "id": 102263,
                "name": "Skorpyron",
                "lfrKills": 1,
                "lfrTimestamp": 1485467992000,
                "normalKills": 2,
                "normalTimestamp": 1485543181000,
                "heroicKills": 8,
                "heroicTimestamp": 1488996601000,
                "mythicKills": 5,
                "mythicTimestamp": 1489607839000
            }, {

The data above they both use bosses and they are both under raids under progression.

So is there a way for me to differentiate between them when i use 

varname = JSON.stringify(response.data.progression.raids.bosses.id)

so that i may later use a case switch statement later
switch (varname)
{
Case 'id for Normal Skorypon': NH Normal progression = NH Normal progression + 1
Case 

Thanks again.

**Comment by benweier** [comment]
@nkane1997 you're not harassing, I'm happy to assist you!

Because the raid response is an array you don't access the values the same way as objects. Objects use named keys (`name`, `id`, etc) that you access using that key but you access array values using the index of their location within the list (`0` for the first, `1` for the second, and so on)

To get the first `raids` object you would do

 ```
const raid = response.data.progression.raids[0]; // raid at location "0"
```

and then access the properties of that raid

```
console.log(raid.name); // => Molten Core
console.log(raid.id); // => 2717
```

The second `raids` object

 ```
const raid = response.data.progression.raids[1]; // raid at location "1"
```

and then access the properties of that raid

```
console.log(raid.name); // => Blackwing Lair
console.log(raid.id); // => 2677
```

To make this easier to work with you can use loops to go through the `raids` array one by one and access each raid object.

```
for (let index = 0; i < response.data.progression.raids.length; i++) { // Go over all `raids` objects and increases the `index` value by one each time
  let raid = response.data.progression.raids[index]; // Gets the raid object at location `index`
  console.log(raid.id, raid.name); // Output `id` and `name`
}
```

This will produce

```
2717 Molten Core
2677 Blackwing Lair
1234 Onyxia
5678 Naxx
...
```

I hope this helps you do what you need

**Comment by nkane1997** [comment]
Thanks again for the quick reply.

This is a big help as it lets me post the names of the raids etc however i am unable to access the data inside still.

e.g.
        "bosses": [{
            "id": 11502,
            "name": "Ragnaros",
            "normalKills": 0,
}]

When i try and state that i would like it to report that data it comes back as undefined.

console.log(raid.id, raid.name, raid.bosses.normalKills)

Returns: 2717 Molten Core Undefinied

In my case i have taken the example you have provided above and used vars instead of lets as i want to use the data else where.

var raid = []
var index = ''
for (index = 0; index < response.data.progression.raids.length; index++) { 
  raid = response.data.progression.raids[index];
  console.log(raid.id, raid.name, raid.bosses.normalKills);
}

To check whether it was actually pulling that data i did just (raid.bosses) and it displayed the data like so:

[{
            "id": 11502,
            "name": "Ragnaros",
            "normalKills": 0,
}]


However it won't allow me to step inside and grab the data? Is this because when i am trying to grab the data is it because i am just typing out the wrong tags?

Thanks again for all your help so far.

**Comment by benweier** [comment]
Hi @nkane1997 
The `bosses` value is an array as well (denoted by the square brackets `[]`) with each boss value being an object (denoted by the curly brackets `{}`). You can access the bosses the same way as accessing the `raids` values.

```
console.log(response.data.progression.raids[0].bosses[0].name) // => Ragnaros
console.log(response.data.progression.raids[0].bosses[0].normalKills) // => 0
```

**Comment by nkane1997** [comment]
Once again absolutely superb.

I have managed to apply the information you have given me to pull the data required.

Progress Report :D https://gyazo.com/3e1a95c3a4cfbd565f339f04dfdd652a

It seems so far that most issues i have been having have just been lack of understanding in regards to how to actually fetch the data. You have been a massive help.

There are now only 3 fields left to fill so hopefully i will be able to get that done.

If not you might get a message or two xD (sorry about that)

Either way I shall let you know when its done and will definitely reference you in my bot.

Thanks.

**Comment by nkane1997** [comment]
https://gyazo.com/a42bc54a68e945c7a4be4dc8d67d4109 

Finished it minus the best key but I am happy with how it is now.

Once again you have been amazing. Thank you very much for the prompt responses over the past few days.

I have mentioned blizzard.js at the bottom of the bot when it replys to the command.

Thanks!
