### ISSUE TITLE
Add support for client credentials flow

### ISSUE THREAD

**Issue by markhaehnel** [benweier/blizzard.js#45]
Authorization for the new Game Data endpoints (#44) is now accomplished via OAuth access tokens.
It would be nice to have the client credential flow implemented in this library to retrieve an access token.

More details here: https://dev.battle.net/docs/read/oauth#ClientCredentialsFlow

**Comment by benweier** [comment]
Ability to request an application token is now available with `2.0.1`. Let me know if you have any issues!
