### ISSUE TITLE
Item level of WoW Charater

### ISSUE THREAD

**Issue by Kopertje** [benweier/blizzard.js#53]
Hello,

I cant seem to get the total (eqquiped) item level with this blizzard.js.
Other data i can get just not the item level. Does anyone has a solution for this?

Groet,
Kopertje

**Comment by markhaehnel** [comment]
Just use the WoW character endpoint with the `items` key like this:
```js
blizzard.wow.character(['items'], { realm: 'proudmoore', name: 'kailee', origin: 'us' })
```
The result data contains the `item.averageItemLevel` and `item.averageItemLevelEquipped` properties.

**Comment by benweier** [comment]
@Kopertje this is the correct solution. I hope it has helped you :)
