### ISSUE TITLE
credentials (us) not working

### ISSUE THREAD

**Issue by fredriklindell** [benweier/blizzard.js#55]
using: const credentials = await blizzard.get().data.credentials({id: battleNetApiKey, secret: battleNetApiSecret, origin: 'us' })

gives me attached error. what am i doing wrong?

thanks in advance!
[credential-error-output.txt](https://github.com/benweier/blizzard.js/files/1346991/credential-error-output.txt)

**Comment by benweier** [comment]
Hi @fredriklindell 

The correct method for requesting OAuth tokens is `blizzard.data.credentials({ origin: 'us', id: BLIZZARD_CLIENT_ID, secret: BLIZZARD_SECRET_KEY })`

**Comment by fredriklindell** [comment]
Alrgiht, so blizzard.data.credentials({id: battleNetApiKey, secret: battleNetApiSecret, origin: 'us' }) should work? I am using the same credentials as this page https://dev.battle.net/io-docs automatically filled when logged in. Are they the correct ones?

Thanks in advance

**Comment by benweier** [comment]
Yes, that should work. Let me know if you have any other issues!

**Comment by fredriklindell** [comment]
Seems like version 2.0.1 also fixes this issue. Great work and many thanks :)
