### ISSUE TITLE
Getting character or guild with keys

### ISSUE THREAD

**Issue by WFrancois** [benweier/blizzard.js#6]
Hi !

I'm currently trying to build an application in node.js, but I have a problem in the blizzard.wow.character part.

I try to get the achievements of a member, but it doesn't seem to work, here's my code : 
`const blizzard = require('blizzard.js').initialize({ apikey: API_KEY });
blizzard.wow.character(['profile', 'achievements'], { realm: 'Sargeras', name: 'Isak', origin: 'eu' })
  .then(response => {
    console.log(response.data);
  });
`

It doesn't throw any warning, just return the basic data : 

> { lastModified: 1477672730000,
  name: 'Isak',
  realm: 'Sargeras',
  battlegroup: 'Embuscade / Hinterhalt',
  class: 10,
  race: 10,
  gender: 1,
  level: 110,
  achievementPoints: 19590,
  thumbnail: 'sargeras/168/106068392-avatar.jpg',
  calcClass: 'f',
  faction: 1,
  totalHonorableKills: 526 }

Here is my package.json for blizzard.js : 
> "blizzard.js": "^1.3.0"

Thanks for your work anyway ! :)

**Comment by benweier** [comment]
Thanks @WFrancois I'll take a look into it

**Comment by benweier** [comment]
@WFrancois I've just published `1.4.0` to resolve this issue. Please update and let me know if there's anything else :)

**Comment by WFrancois** [comment]
@benweier Works great ! Thank you for your work  ! :)
