### ISSUE TITLE
Code 403: Account Inactive

### ISSUE THREAD

**Issue by ForrestMcIntyre** [benweier/blizzard.js#66]
I am trying to get the stats for Healmycrits-Dalaran (US)

If I use the URL in a browser (https://us.api.battle.net/wow/character/dalaran/Healmycrits?fields=statistics&locale=en_US&apikey=BLIZZARD_API_ID) it works correctly and returns the intended JSON
```
{
  "lastModified": 1518328740000,
  "name": "Healmycrits",
  "realm": "Dalaran",
  "battlegroup": "Rampage",
  "class": 2,
  "race": 10,
  "gender": 0,
  "level": 110,
  "achievementPoints": 15685,
  "thumbnail": "dalaran/49/176616497-avatar.jpg",
  "calcClass": "b",
  "faction": 1,
  "statistics": {...},
  "totalHonorableKills": 82
}
```
But when I try to use blizzard.js on anything that doesn't require an `access_token` then I get the response
``` { code: 403, type: 'Forbidden', detail: 'Account Inactive'} ```

The following is my attempt at the code. The commented out Mythic Stats work, but retrieving the stats for Healmycrits below returns the Code 403 JSON. 
```
var express = require('express');
var router = express.Router();
const blizzard = require('../config/blizzard');

var access_token;

/* GET home page. */
router.get('/', function(req, res, next) {
  var locale = req.query.locale;
  var mounts;
  blizzard.data.credentials({id: 'BLIZZARD_API_ID', secret: 'BLIZZARD_API_SECRET', origin: 'us' })
  .then(response => {
    access_token = response.data['access_token'];
    console.log(access_token);
    blizzard.data.validate({ origin: 'us', token: access_token })
      .then(response => {
        console.log(response.data);

        // blizzard.data.mythicChallengeMode({ access_token: access_token, namespace: 'dynamic-us', origin: 'us' })
          // .then(response => {
          //   console.log(response.data);
          // })
          // .catch(err => console.log(err.response.data));

        blizzard.wow.character(['profile'], { name: 'Healmycrits', realm: "dalaran"})
          .then(response => {
            console.log(response.data);
          })
          .catch(err => console.log(err.response.data));
      })
      .catch(err => console.log(err.response.data));
  })
  .catch(err => console.log(err.response.data));

  res.render('stats', { title: 'Express', mounts: mounts });
});
```
I know I'm doing something wrong but I've been looking at the code for too long and can't figure it out 

Thanks in advance :)

**Comment by benweier** [comment]
Do you mind pasting the `../config/blizzard` code here @ForrestMcIntyre. I suspect `blizzard.js` isn't being initialised with your API key. `mythicChallengeMode` works because the API key is manually provided to `credentials` which gives you a fresh access token on every request. The `character` request will use the API key you initialise with (in this case it's not being set) unless you override it.

You've got two choices:
```
// config/blizzard.js
module.exports = blizzard.initialize({
  apikey: BLIZZARD_API_ID // this gets used by default for all resource requests
});
```
or
```
blizzard.wow.character(['profile'], { name: 'Healmycrits', realm: 'dalaran', apikey: BLIZZARD_API_ID })
  .then(response => {
    console.log(response.data);
  })
  .catch(err => console.log(err.response.data));
```

**Comment by ForrestMcIntyre** [comment]
**config/blizzard.js**
```
const blizzard = require('blizzard.js').initialize({
  apikey: BLIZZARD_API_ID,
  origin: 'us'
});
module.exports = blizzard;
```

Also trying option 2 with the key directly in the `blizzard.wow.character()` call still yields the same response

**Comment by ForrestMcIntyre** [comment]
Deleted the application due to another issue and forgot to update key. Working now that I'm using the correct key
