### ISSUE TITLE
Getting WoW Realm List

### ISSUE THREAD

**Issue by dnorthrupva** [benweier/blizzard.js#7]
Hello,

I'm having issued getting a response from any GET requests for wow/realm list.

I've tried with/without region, /wow/realm/status as specified in the document, and numerous variations of it. What is the end point for a list of realms?

**Comment by benweier** [comment]
HI @dnorthrupva, what's the issue you're having? Does the promise return anything in the response?

```js
// All US realms
blizzard.wow.realms({ origin: 'us' })
  .then(response => {
    console.log(response.data);
  })
  .catch(err => {
    console.log(err.response.data);
  });
```

**Comment by benweier** [comment]
I've looked into this further and there shouldn't be any problems fetching the full realm list. However there was an issue affecting fetching a list of realms which is now resolved in `1.5.0`. Let me know if this doesn't work as expected for you

**Comment by dnorthrupva** [comment]
Thanks for the speedy reply.

It must be a poor use of it on my end - In which file are you calling the 'blizzard.wow.realms' function? I've been trying quite a bit but struggling to figure out the proper flow.

The only ones I'm using successfully are going to the end-point of my domain.

For instance {{mydomain}}/wow/en/character/{server}/{name}
Which feels completely wrong.

It's definitely user error. I tried initializing a controller to just render 'blizzard.wow.character' but it doesn't work.

However, putting the blizzard.wow.character inside of the server.js does prompt Node upon opening to retrieve the data.

**Comment by benweier** [comment]
I'm not sure what you mean. Could you paste a snippet of the code you're having trouble with?

You can also take a look at my [example app](https://github.com/benweier/blizzard.js/tree/example) to see a sample of what to do.

**Comment by dnorthrupva** [comment]
Yea, wording it is obviously proving an issue. I did clone the example app - https://demoappagain.herokuapp.com/ - But all I was able to leverage of it was the end-points for it.

So while  fetching {{mydomain}}/wow/en/character/{server}/{name} works, I'm obviously having issues leveraging your functions.

So for instance I have Users.js(Controller) - I'd like to make it so this page 'always' loads the person character.


> 'use strict';
> 
> const express = require('express');
> const router = express.Router();
> const account = require('../routes/account');
> const wow = require('WoW');
> const sc2 = require('../routes/sc2');
> const d3 = require('../routes/d3');
> const blizzard = require('../config/blizzard.js');
> const app = express()
> router.get('/Users', function(req, res, next) {
>   blizzard.wow.character(['profile'], { origin: 'us', realm: 'Thrall', name: 'Suzaka' })
>       .then(res => {
>         console.log(res);
>       });
>     res.json(posts);
>   });
> });

This is a snippet - I was trying to just get the call to respond on /Users.

Like I said, I can do a very similar script to that on Server.js (without the route) and it DOES respond with the API as I would expect.

I'm mostly just trying to understand 'where' to 'call the function'. 

If I'm missing something from the example app, feel free to let me know. I wasn't really sure what to do with it besides test end points.

**Comment by benweier** [comment]
The first thing I notice is that your express app isn't being told to use `router` so it doesn't know that the '/Users' route exists and can't listen or respond to requests on that path. You're also telling the '/Users' route to return `res.json(posts)` before the blizzard.js promise has a chance to settle (but `posts` is undefined).

Your first change should be remove `res.json(posts)` so that the route doesn't attempt to send an undefined response.

Secondly, mount your routes with `app.use` so express knows which paths to match.

```
// Create a route for the 'Users' path
const users = router.get('Users', function(req, res) {
  return blizzard.wow.character(['profile'], { origin: 'us', realm: 'Thrall', name: 'Suzaka' })
    .then(response => res.json(response.data);
});

// Mount the 'Users' route to `/`
app.use('/', users);
```

This example will return profile data for the Suzaka-Thrall character when you hit the `/Users` path.

**Comment by dnorthrupva** [comment]
I really appreciate you taking the time to reply. I feel stupid for how simple my question is.

Your code snippet led me on the right path. I finally managed to get a page response by placing 

> app.get('/Users', function( req, res){
>   return blizzard.wow.character(['profile'], { origin: 'us', realm: 'Thrall', name: 'Suzaka' })
>     .then(response => res.json(response.data))
> }); 

inside of 'server.js' - I will try to see why putting this inside of User/Bans.js etc etc wouldn't work.

Appreciate all the help. Look forward to using this a lot more.

**Comment by benweier** [comment]
Glad I could help! Good luck 👍
