### ISSUE TITLE
Migration to Blizzard Battle.net Developer Portal

### ISSUE THREAD

**Issue by rejas** [benweier/blizzard.js#75]
Blizzard announced depreacting the old mashery portal and switching all api access over to their own new portal. 
Are you aware of this and will there be changes necessary to this library and apps that use this?

**Comment by rejas** [comment]
FYI: https://develop.battle.net/documentation/guides/migration-guide

**Comment by benweier** [comment]
I have started work on it. Currently figuring out a bit of a restructure/reviewing changes to the Game Data endpoints and namespaces. I appreciate the offer, although I'm not sure what parts can be spun off

**Comment by rejas** [comment]
Good to hear. In any case, if there are "outsourcable" tasks, maybe define them in an issue so we helpers can take a look and weigh in or take them?
Also: once there are develop-branches I am more than willing to test them with my rejas/wowfeed app to see if there are any regressions.

**Comment by jahraphael** [comment]
Hi there, I was just wanting to check in on this migration work to see how things are going. We're wanting to get compliant with the new Battle.Net developer portal before 8.1. I'm happy to contribute development time to the official port if you're at a point where that makes sense. Otherwise, we'll just fork and build our own support for now.

**Comment by rejas** [comment]
I see you started work on migrating to the new dev portal @benweier Is it testable yet and if so, what should one change in the calls to your API? Happy xmas btw :-)

**Comment by benweier** [comment]
Thanks @rejas, Happy Christmas to you as well! I believe I've updated all the endpoints to use the new API and I'm checking on what I've missed in terms of OAuth and the `Authorization` header, the `namespace` query value, and making general improvements to internals.

So far there's no concrete change to `blizzard.js` methods (I'm undecided whether I take this opportunity to rename `apikey` to `key` and `access_token` to `accessToken` or simply `token`) so you should be fine migrating to the new version when it gets published. Due to the risk of these changes, regardless of actual breaking changes, this will likely be published as `3.0.0`

**Comment by rejas** [comment]
Trying out the branch with the new api endpoint i only get a

`Request failed with status code 401`

Unauthorized-error.  I created a client on the new site and updated my apikey with the new client secret. Do I miss something here?

**Comment by benweier** [comment]
Yeah I've just run into that myself and have fixed it. The new API portal accepts either a `access_token` query parameter or the `Authorization` header and it's no longer based on the `apikey` query parameter. I'll push a few more commits soon before calling it a night.

**Comment by benweier** [comment]
I'm sorry, I lied earlier. There will be changes to the API, but all in the hopes of simplification and consistency.

`initialize` now accepts these object properties as its first argument:
```
origin [us|eu|etc]
locale [en_US|en_GB|etc]
id (the API client ID)
secret (the API client secret)
token (an existing access token fetched from `.data.credentials()`)
```
These properties now form the base default values for _all_ requests going through `get`/`fetchToken`/`checkToken`. If any required property is missing from an API method (e.g. /wow/character) it will be pulled from defaults instead, and these defaults can be overridden for each method simply by passing the key:value in the object argument.

This should maintain compatibility with most, if not all, API methods but I have yet to fully test every single one. I really should do more comprehensive unit tests.

**Comment by rejas** [comment]
No worries about that lying ;-) Still a little confused on how to call the initialize now with regards to the token. Currently I try this:
   ```
 blizzard    = require('blizzard.js').initialize({
        id: 'e244e24098db48dfb1f4ec6d86e4aacb',
        secret: key,
        origin: 'eu',
        locale: 'en-GB'
    }),
```
So how does the `token` param fit into the `initialize`? 
Probably a good idea to call it a v3 (and maybe update the docs too, you need some help with that btw?) Have a good xmas eve etc pp :-) Hohoho!

**Comment by benweier** [comment]
The `token` param is a "pre-initialised" authorisation and isn't required. You could do something to initialise without a token and then set the new default token immediately but I see this as unnecessary boilerplate. You should only need to pass it to `initialize` if you have fetched and stored it somewhere already.

Because a token is now required I'm going to make it automatically fetch a token during `initialize` so that you don't need to.

**Comment by benweier** [comment]
There's been a lot of movement today. The `id` property conflicted with a few different API methods and it wasn't clear whether the value in the `get` call after merging with defaults was the client ID or a parameter to the original function (like in the case of `blizzard.wow.achievement({ id: undefined })`.

So I've renamed the client `id` property to `key` and significantly cleaned up argument handling of all API methods to prevent passing values that don't have any relevance to the request configuration.

**Comment by rejas** [comment]
Looks like some work still to do, your builkds are currently failing... Well, lets rest until 2019 but not longer ;-)

**Comment by benweier** [comment]
Lots of work done today... we're getting close now. Just got to make a pass over the Starcraft methods, update documentation, and add a migration guide.

**Comment by benweier** [comment]
I'm reasonably confident this is ready for testing. Be aware there have been significant changes to many API methods. I'm going to write full documentation and migration after the new year.

**initialise**
```
blizzard.initialize({
  key: process.env.BLIZZARD_CLIENT_ID,
  secret: process.env.BLIZZARD_CLIENT_SECRET,
  token: BLIZZARD_APPLICATION_TOKEN, // more on this further below
});
```

All previous `blizzard.data` methods have been moved into the `blizzard.wow` namespace. Blizzard originally just called them "Game Data APIs`" so they were put under `.data`. Now that they have standardised their own game data scopes (WoW Game Data/SC2 Game Data/D3 Game Data) all the game data methods now sit under their respective namespaces alongside the community data API methods.

**credentials** and **validate**
The `blizzard.data.credentials` and `blizzard.data.validate` methods have been moved to `blizzard.getApplicationToken` and `blizzard.validateApplicationToken`, and they function the same way.

`blizzard.getApplicationToken` returns an **application token** that follows the _client credentials code flow_ and is used for game data APIs while the **user token** follows the _authentication code flow_. I haven't implemented the user authentication code flow for complexity reasons. It's more reliable getting the user to authorise your application via passport and the passport-bnet strategy (or other oauth solution) and will integrate better with your web app than I possibly could.

You can pre-initialise `blizzard.js` with a previously issued application token or do it manually.

```
const blizzard = require('blizzard.js').initialize({
  key: process.env.BLIZZARD_CLIENT_ID,
  secret: process.env.BLIZZARD_CLIENT_SECRET,
});

blizzard.getApplicationToken()
  .then(response => {
    // save `response.data.access_token` to your database or some kind of persistent storage
  });

// OR

blizzard.getApplicationToken()
  .then(response => {
    blizzard.defaults.token = response.data.access_token;
  });
```

**Comment by benweier** [comment]
Hope everyone has a great new year!

**Comment by rejas** [comment]
Good news: Works for my char feeds, Bad news: some issues with my guild feeds, still investigating though. Just wanted to give a big thanks for your work and a happy new year to you!!!!! CU 2019!

**Comment by Nerothos** [comment]
I'm going to have a go at this too.
Thanks for updating it and happy new year !

**Comment by fredriklindell** [comment]
Hi, when running:

```
blizzard.validateApplicationToken( { token: 'application_token'  })
```

i get the following error: **Required String parameter 'token' is not present**

**Comment by Nerothos** [comment]
![image](https://user-images.githubusercontent.com/3739096/50564183-425e3f00-0d23-11e9-9759-6ac98d901753.png)
Webstorm tell me that it need an origin parameter, maybe try adding it?

**Comment by fredriklindell** [comment]
No the problem is that the validateApplicationToken function in blizzard.js does not add the the 'token' query param as this page states: https://gist.github.com/erorus/6c08227921ff99d93295fa9f91c7fd70

**Comment by fredriklindell** [comment]
This solves the problem:

```
Blizzard.prototype.validateApplicationToken = function validateApplicationToken(args) {
  const { origin, token } = pick(merge({}, this.defaults, args), ['origin', 'token']);

  return this.axios.get(`https://${origin}.battle.net/oauth/check_token?token=${token}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'User-Agent': `Node.js/${process.versions.node} Blizzard.js/${this.version}`,
    },
  });
};
```

**Comment by benweier** [comment]
The docs at https://develop.battle.net/documentation/api-reference/oauth-api prefer the use of the `Authorization` header over the query parameter for security. It appears this request doesn't like the missing query parameter so I'll update to use the query and try and report it to the API team.

**Comment by rejas** [comment]
Guild feed issues disappeared today, dont know why :-) So from my side (https://wowfeed.herokuapp.com/) I would be ready to switch :-) 
Anybody else has problems with the stability of the https://develop.battle.net/access site? Sometimes I get error messages on that webpage ...

**Comment by czbaker** [comment]
I'm currently getting 401 errors when trying to use this library to access stuff in a GraphQL query, and I know that I've got a good token and stuff.

Is this because the version I've installed from Yarn doesn't incorporate the migration to the new Dev Portal?  (I don't know if the NPM version has that).

If this is the case, how do I go about fixing this, since it seems that migration has mostly already been done?

**Comment by rejas** [comment]
You have to install the updated branch, your package.json has to have this entry:
`    "blizzard.js": "https://github.com/benweier/blizzard.js.git#issue-75",`

Then an `npm install` (or `yarn install`) will get the updated code. Since the updated code isnt released on npm yet, this is the only way to test out the new API

**Comment by czbaker** [comment]
Thank you so much for the super quick response!   Doing that now.  :)

**Comment by czbaker** [comment]
So, when I try to use the new version, I had to update/patch the Endpoint URL for `blizzard.account.user` (was getting a 404 error) as the URL has changed according to docs.

After I fixed that, I continue to get 401 errors, despite being sure that my keys and stuff are valid and that I switched over to the "new" `initialize()` method that takes key/secret instead of the Mashery version.

Attached is the code I'm using, not sure what I'm doing wrong, it's probably user error?

```
import { ApolloError } from "apollo-server-core";
import blizzardjs from 'blizzard.js';

const key = process.env.BNET_ID;
const secret = process.env.BNET_SECRET;

const blizzard = blizzardjs.initialize({
    key,
    secret,
    origin: "us"
});

const resolvers = {
    Query: {
        hello: (_, args, context) => {
            console.log(context);
            return "World!";
        },
        getTag: (_, args, context) => { 
            if (context.user) {
                const access_token = context.user.token;
                console.log(access_token);
                return blizzard.account.user({ access_token })
                    .then((response) => {
                        console.log(response.data);
                    })
                    .catch((err) => {
                        throw new ApolloError(err);
                    })
            } else {
                throw new ApolloError('Not logged in!');
            }
        }
    }
};

export default resolvers;
```

**Comment by Nerothos** [comment]
> 
> 
> The docs at https://develop.battle.net/documentation/api-reference/oauth-api prefer the use of the `Authorization` header over the query parameter for security. It appears this request doesn't like the missing query parameter so I'll update to use the query and try and report it to the API team.

Regarding the token I found something on the discord quoting :

> Schiller - 12/26/2018
> If you look up the OAuth2 specification (https://tools.ietf.org/html/rfc6749) you'll see that every token endpoint is treated as a post request with content type of  x-www-form-urlencoded. They are not protected resources as the other endpoints, in which you can actually use a bearer token. Section 3.2 say token endpoints must be a POST request with relevant parameters.
> 
> fightn-ares 12/26/2018
> Ok cool. Yeah it's working fine hitting the check endpoint with the token as a post request with the token in the body. I was just confused because the docs suggested being sure to pass it as a header, but there's also some discrepancies where the endpoints are listed as GETs when suggested use is actually POST.

It apparently should be sent in the body and not the header? I hope this help

**Comment by benweier** [comment]
Thanks guys, the `validateApplicationToken` method now uses POST with `token` in the body. I have confirmed this to work locally.

@czbaker I apologise, I've fixed the URL and changed the `blizzard.account.user` method to `blizzard.account.userInfo` for consistency with the Blizzard API docs. Your blizzard.js usage should now be

```
const token = context.user.token;
return blizzard.account.userInfo({ token })
    .then((response) => {
        console.log(response.data);
    })
    .catch((err) => {
        throw new ApolloError(err);
    })
```

**Comment by Nerothos** [comment]
Oh ok, I've tried with body: {token:${token}} so that's why it didn't work 🤣
Nice that it's working without url param 👍

**Comment by AlexZeDim** [comment]
According to Blizzard email, Mashery API will be shut down in couple of days. Do you have plans to merge this branch `75` with `master `?

**Comment by benweier** [comment]
Absolutely! I expect to merge PR #79 in ~6hrs. Unfortunately my laptop is going in for repairs tonight and I won't get it back until the 7th, so that kinda forced my hand when I was planning to publish 3.0.0 tomorrow. Documentation + migration can be finished from the web UI over the weekend...

**Comment by benweier** [comment]
`3.0.0` is now published to npm. API documentation has been removed to avoid confusion, it will be added as soon as I can finish writing it.

**Comment by fredriklindell** [comment]
Great work! Many thanks 😊

**Comment by Nerothos** [comment]
Thanks for your work !
