### ISSUE TITLE
Unable to pull Account Data post sync

### ISSUE THREAD

**Issue by dnorthrupva** [benweier/blizzard.js#8]
I'm trying to use the passport_bnet package Blizzard released so that the flow would be:

Authorize -> Get token + id + BTag -> Feed token into /account/us/user endpoint.

This flow works when I go to https://us.api.battle.net/account/user?access_token=~~~~~ end point directly, but not when I use the wrapper.

Thoughts/insight? I'm just continuously getting 403/Forbidden on the hit. I'm thinking it's due to an callback issue, but wondering if you've seen these two combined.

Other-wise, how do you get the token of a user to actually receive their battle_tag/characters?

**Comment by benweier** [comment]
Thanks @dnorthrupva can you paste a code snippet of how you're using `blizzard.account.user()`?

**Comment by dnorthrupva** [comment]
Sure! So that's actually where part of my issue is.

```
`passport.use(new BnetStrategy({
    clientID: BNET_ID,
    clientSecret: BNET_SECRET,
    callbackURL: "https://testbjsoauth-dnorthrup.c9users.io/auth/bnet/callback",
    region: "us"
}, function(token, refreshToken, profile, done) {
    return done(null, profile);
    /*
         blizzard.account.user({ token, origin, locale })
           .then(response => res.json(response.data))
         .catch(err => res.json(err.response.data));
    */
}));`
```

Obv the commented out portion is what I found in the source to call it via your package.
The return done ATM is returning the account_id and the battletag. It's using the person who 'authorized'ed it's token to pull it.

Mainly I'm just confused on how to pull it in this sense. Oauth is working, but like I said - I'd love for post-auth for it to populate the characters

**Comment by solfolango** [comment]
Same here, using passport-bnet also. I use it a bit differently:
```
app.get('/auth/bnet/callback', passport.authorize('bnet', { failureRedirect: '/' }), function(req, res) {
   // req.account has a .token field I assumed would be the access token granted by the oauth provider
   console.log(req.account);

   blizzard.account.wow({ token: req.account.token, origin: 'eu', locale: 'de_DE' })
      .then(response => {
         res.send(response.data);
         console.log(response.data);
   });
```

Response by node:

> (node:18859) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 401
> (node:18859) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

Querying a single wow character not related to the user is working fine, no problems with that one.

**Comment by benweier** [comment]
Thanks for the reports! I'm working on a fix for the access token woes.

**Comment by benweier** [comment]
I have just published `1.6.0` to resolve this issue. The only change is the `token` parameter is now `access_token` to match the request parameter expected by the API.

**Comment by solfolango** [comment]
Thanks for the fix, I can confirm it's working now. 

Perhaps you should adjust the documentation to reflect the change that we need to use access_token instead of token in blizzard.account.wow({ ...})?

**Comment by benweier** [comment]
Thanks @solfolango I thought I fixed all the docs.. Will take care of it now
