### ISSUE TITLE
How to - Angularjs

### ISSUE THREAD

**Issue by dgateles** [benweier/blizzard.js#80]
Im trying to include that in a angularjs project, but without success.
How to add this component on a angularjs project?

**Comment by benweier** [comment]
It's possible to include `blizzard.js` in a front-end project, although it's not recommended. Your client ID and Secret keys are necessary for some functionality and should be kept private at all times. There is no ESM bundle of the library so you'll need to make sure CommonJS modules work with your build process.

With that said, you would require and initialise `blizzard.js` the same way, but to keep the ID and Secret private you wouldn't pass them to `.initialize()`. I suggest using your own API to fetch an access token (maybe look into a serverless function like AWS Lambda or Google Cloud Functions if you don't already have an API) that you pass to your front-end and then initialise `blizzard.js` with just the token.

Once you've got the token there's nothing really stopping it from being able to fetch data, aside from possibly CORS or other cross-domain related security measures.. I haven't really checked if jsonp is needed or supported by the new API portal. Just note that there is a dependency on the internal Node `querystring` module that you should install as a peer dependency.
