### ISSUE TITLE
World of Warcraft Game Data API Update - Patch 8.2

### ISSUE THREAD

**Issue by AlexZeDim** [benweier/blizzard.js#92]
Blizzard [announced](https://us.battle.net/forums/en/bnet/topic/20772337044) new endpoints for game data a couple of days ago, guess we should update `blizzard.js`, right? 

And if the answer is `yes` then how should we do this? I could open [new PR#95](https://github.com/benweier/blizzard.js/pull/95) with (my) updates, but the problem is, that some new game data endpoints are named exactly the same as (old)-community ones. Especially items, so what is the best option:

- merge current `WoW.prototype.item` request with new endpoint, like item:id/item:set 

```
WoW.prototype.item = function getItem({ id, set = false, bonuses, ...args }) {
  const path = set ? `/wow/item/set/${id}` : `/wow/item/${id}`;

  return this.blizzard.get(
    path,
    merge({}, args, {
      params: {
        ...(bonuses ? { bl: bonuses.toString() } : {}),
      },
    }),
  );
};
```

- or add a new one and name it in a new way, like this one: 

```
WoW.prototype.itemData = function getItemData(id, ...args) {
  return this.blizzard.get(
    `/data/wow/item/${id}`,
    merge({}, args, {
      namespace: 'static',
    }),
  );
};
```

**Comment by AlexZeDim** [comment]
Btw, the key feature of item data endpoint is supporting multi language, so instead of sending each request to endpoint with one `locale` we could send just one and receive a multi-language response like this:
```"name": {
    "en_US": "Osmenite Ore",
    "es_MX": "Mena de osmenita",
    "pt_BR": "Minério de Osmenita",
    "de_DE": "Osmeniterz",
    "en_GB": "Osmenite Ore",
    "es_ES": "Mena de osmenita",
    "fr_FR": "Minerai d’osménite",
    "it_IT": "Minerale di Osmenite",
    "ru_RU": "Осменитовая руда",
    "ko_KR": "오스미나이트 광석",
    "zh_TW": "奧司曼礦石",
    "zh_CN": "透金矿石"
  },
...
```
But unfortunately locale dependency of `Blizzrard.js` won't let us to do this, because locale parameter for axios requests is fixed in file `blizzard.js` in row 218:
```
    params: {
      ...params,
      locale: endpoint.locale, //here is defined locale for requests
      ...(namespace ? { namespace: `${namespace}-${origin}` } : {}),
    },
```
and it defined from allowed array from `endpoints.js`, so if we add another value in this array, for example like:
```
  us: {
    hostname: 'https://us.api.blizzard.com',
    defaultLocale: 'en_US',
    locales: ['en_US', 'es_MX', 'pt_BR', 'any'],
  }
```
and then send our request with `locale:any` we will receive multi-language response, instead of a certain one

**Comment by benweier** [comment]
Thanks @AlexZeDim I'll check this out

**Comment by benweier** [comment]
It seems there have been a number of features and APIs added in the last few months, and since I'm not as active in the Blizzard API space as I used to be I rely on issues like this to be opened to be made aware of them. I'll review all the new APIs and add them as soon as possible.

**Comment by AlexZeDim** [comment]
@benweier if I could help you with that, just say me and I'll cover all necessary endpoints. But I need to know how you, as a `maintainer`, prefer to see pattern/structure for new endpoints

**Comment by benweier** [comment]
Part of the challenge which you already mentioned is that some of the new Data APIs already exist in the Community APIs.

I wonder if Blizzard intends to phase out all Community APIs with a Data API equivalent? If so, should I move deprecated APIs to a "legacy" namespace? If not, should I split the APIs by "community" & "data" namespaces?

I might have to ask around before defining how new endpoints get implemented.

**Comment by AlexZeDim** [comment]
Okey, I understood that. 

If my vote counts, I definitely vote for `split` because `data` and `community` endpoints are providing not the same/equal data. For example, `item` community endpoint has more rich description with `icon`, `stackable` and other properties and the new `item` data don't have even 70% of them, but have multi-lang names and so on.

So they perfectly complement each other.

**Comment by rejas** [comment]
Looks like the Community endpoints now longer exist: https://develop.battle.net/documentation/world-of-warcraft/community-api-migration-status
So migrating to the new endpoints needs to be done sicne my RSS feed doesnt work now anymore.
How can I help :-) ?
